### ISSUE TITLE
R&C screen artifacting

### ISSUE THREAD

**Issue by superwisemon** [Rinnegatamante/reRescaler#5]
Hello!

I've done some testing for games that won't work using this plugin, and I wondered if there was some blacklist functionality to get this to stop running in the problem games.

Ratchet and Clank Trilogy has screen artifacting in the form of some white lines all over the screen. Also some gnarly screen tearing.

Also, Borderlands 2, when downscaled with vitagrafix, cannot be rescaled up and will resort in a garbled mess.

**Comment by Rinnegatamante** [comment]
In general, you can prevent some games to run certain plugins by properly editing your tai config file: https://github.com/DaveeFTW/taihen-parser/blob/master/README.md (Look at Halt Point section)
